global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'nickclonemail1@gmail.com'
  smtp_auth_username: 'nickclonemail1@gmail.com'
  smtp_auth_password: 'dxki gtxy zywx wykq'
  smtp_require_tls: true
route:
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'superkklot2001@gmail.com'
        send_resolved: true