# my global config
global:
  scrape_interval: 5s 
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "jenkins_rules.yml"
  - "loki_rules.yml"
  - "prometheus_rules.yml"
  - "nginx_rules.yml"
  - "promtail_rules.yml"

# Here it's Prometheus itself.
scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ['192.168.28.38:9100']
  - job_name: "loki"
    static_configs:
      - targets: ['192.168.28.38:8001']
  - job_name: "alertmanager"
    static_configs:
      - targets: ['192.168.28.38:8081']
  - job_name: "promtail"
    static_configs:
      - targets: ['192.168.28.38:8002']
  - job_name: "fastapi"
    static_configs:
      - targets: ['192.168.28.38:8085']