# my global config
global:
  scrape_interval: 5s 
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "jenkins_rules.yml"
  - "loki_rules.yml"

# Here it's Prometheus itself.
scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ['host.docker.internal:9100']
  - job_name: "loki"
    static_configs:
      - targets: ['host.docker.internal:3100']
  - job_name: "alertmanager"
    static_configs:
      - targets: ['host.docker.internal:9093']
  - job_name: "promtail"
    static_configs:
      - targets: ['promtail:9080']
  - job_name: "fastapi"
    static_configs:
      - targets: ['host.docker.internal:8085']