version: '3.8'

services:
  backend:
    build:
      context: ..  
      dockerfile: models/Dockerfile
    container_name: fastapi_backend
    ports:
      - "8085:8085"
    networks:
      - app-network

  frontend:
    build:
      context: ../Front_end
    container_name: react_frontend
    ports:
      - "3006:3006"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
